# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='category_ref',
            new_name='category',
        ),
    ]
