# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170623_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='quote',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
