# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20170727_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
